name: mynotesfire
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  shared_preferences: ^2.3.5
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  cloud_firestore: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

